# Generated by Django 3.0 on 2021-10-23 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='feed',
        ),
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
