# Generated by Django 3.0 on 2021-10-23 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211023_1244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
