# Generated by Django 3.0 on 2021-10-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='feed_link',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
    ]
