# Generated by Django 3.0 on 2021-10-29 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_feed_feed_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='owener',
            new_name='owner',
        ),
    ]
